- name: "Authenticate AWS CLI with AWS"
  hosts: management
  user: ubuntu
  gather_facts: false
  become: yes
  vars:
    - ACCESS: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
    - SECRET: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
    - REGION: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"
  tasks:
    - name: Set the aws_access_key_id
      shell: "aws configure set aws_access_key_id {{ ACCESS }}"
    - name: Set the aws_secret_access_key
      shell: "aws configure set aws_secret_access_key {{ SECRET }}"
    - name: Set the default.region
      shell: "aws configure set default.region {{ REGION }}"