---
- hosts: management
  gather_facts: False
  tasks:
    - name: Ansible playbook to retrieve environment variables on linux servers.
      debug:
        msg: "Second method: {{(lookup('env','HOME'))}}"