apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-pickcolor-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone-pickcolor
  template:
    metadata:
      labels:
        app: capstone-pickcolor
    spec:
      containers:
        - name: capstone-pickcolor
          image: kunal78/capstone-pickcolor
          ports:
            - containerPort: 80