# Create web hosts based on docker image

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cde-capstone
spec:
  selector:
    matchLabels:
      app: cde-capstone
  replicas: 4
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cde-capstone
    spec:
      containers:
      - name: cde-capstone
        image: kunal78/cde-capstone
        imagePullPolicy: Always
        ports:
        - containerPort: 80