---

- name: "Download kubectl"
  become: true
  shell:  |
    sudo curl -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.22.6/2022-03-09/bin/linux/amd64/kubectl
  args:
    chdir: $HOME

- name: "Apply execute permissions to the binary"
  become: true
  shell:  |
    sudo chmod +x ./kubectl
  args:
    chdir: $HOME

- name: "Copy the binary to a folder to the $PATH"
  become: true
  shell:  |
    sudo mkdir -p $HOME/bin
    sudo cp ./kubectl $HOME/bin/kubectl  
    sudo export PATH=$PATH:$HOME/bin
  args:
    chdir: $HOME

- name: "Add the $HOME/bin path to the shell initialization file"
  become: true
  shell:  I
    sudo echo 'export PATH=$PATH:$HOME/bin' >> .bashrc
  args:
    chdir: $HOME