---

- name: "Copy kubectl"
  become: true
  copy:
    src: kubectl
    dest: ./bin/kubectl
    owner: ubuntu
    group: ubuntu
    mode: 0755
  #shell: curl -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.22.6/2022-03-09/bin/linux/amd64/kubectl
  #args:
  #  chdir: $HOME

- name: "Apply execute permissions to the binary"
  shell: chmod +x ./kubectl
  args:
    chdir: $HOME

- name: "Copy the binary to a folder to the $PATH"
  shell: mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
  args:
    chdir: $HOME

- name: "Add the $HOME/bin path to the shell initialization file"
  shell: echo 'export PATH=$PATH:$HOME/bin' >> .bashrc
  args:
   chdir: $HOME