- name: Copy service configuration
  become: true
  copy:
    src: "{{ ENVIRONMENT_NAME }}-service.yaml"
    dest: $HOME

- name: Create service configuration
  become: true
  command: "./bin/kubectl apply -f {{ ENVIRONMENT_NAME }}-service.yaml"
  args:
    chdir: $HOME