---
- hosts: management
  vars:
    - AWS_ACCESS_KEY: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
  tasks:
    - name: Printing env variables
      debug:
        msg: "AWS_ACCESS_KEY: {{ AWS_ACCESS_KEY_ID }}"
