---
- name: "Install dependencies"
  hosts: management
  user: ubuntu
  gather_facts: false
  become: true
  pre_tasks:
    - name: "Install 'unzip'"
      apt:
        name: [ "unzip" ]
        state: latest
        update_cache: yes

- hosts: management
  tasks:
    - name: Printing env variables
      debug:
        msg: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
        